# -*- coding: utf-8 -*-
"""Semantic_search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R-Qt_tsjsOYC1TuYNCb-_4BG_dLT6SZm

## **Semantic Search and Recommendation System on Quora Question -Answer Data using Sentence Transformer**

### **Import Necessary Libraries**
"""

import pandas as pd

from sentence_transformers import SentenceTransformer
import faiss

"""### **Dataset Import**"""

ds=pd.read_parquet("/content/drive/MyDrive/0000.parquet")

ds

print(type(ds))

"""### **Dataset Preprocessing**"""

ds.iloc[0,:]

ds['ques_ans']=ds['question']+". " +ds['answer']

ds

"""### **Model Import**"""

quora_embedding = SentenceTransformer('distiluse-base-multilingual-cased-v1')

"""### **Create Corpus Embeddings and Faiss Index**"""

quoraqa_embeddings=quora_embedding.encode(ds['ques_ans'].values)
print(quoraqa_embeddings.shape)

n_cells=1000
num_dimensions=quoraqa_embeddings.shape[1]
quantizer=faiss.IndexFlatL2(num_dimensions)
index=faiss.IndexIVFFlat(quantizer,num_dimensions,n_cells)
index.train(quoraqa_embeddings)
index.add(quoraqa_embeddings)

"""### **Query Embeddings and Semantic Search**"""

query_text="aeroplanes"
query_embedding=quora_embedding.encode([query_text])
num_results=5
distances, indexes=index.search(query_embedding,num_results)

indexes

rele_rows=ds.iloc[indexes[0]]
for i,row in rele_rows.iterrows():
  print("-",row['ques_ans'])

"""We searched using the query "Aeroplanes" and the query text is converted to query embeddings. The faiss index space is searched for text of high cosine similarity between the corpus and query embeddings and the ouput is returned.

As we can infer from the output that, it share close similarity with the word aeroplanes viz.,flight, military pilots, atmosphere, takeoff and landings.

### **Recomendation System**
"""

row_article=ds.iloc[28]

row_article

inp_artquery=row_article['question']

query2_embedding=quora_embedding.encode([inp_artquery])
num_resultss=25
distancess, indexess=index.search(query2_embedding,num_resultss)

rele_rowss=ds.iloc[indexess[0]]
for i,row in rele_rowss.iterrows():
  print("-",row['question'])

"""The above recommendation sysytem was able to suggest similar question on par with the input query. This dataset have repeated question,hence we see duplicates."""